# Generated by Django 3.1.4 on 2020-12-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nombre',
        ),
        migrations.AddField(
            model_name='clientes',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombreOrganizacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombreRepresentante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientes',
            name='run',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
