# Generated by Django 3.1.4 on 2020-12-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0002_auto_20201207_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='celular',
            field=models.IntegerField(blank=True, default=3453, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(blank=True, default=456, max_length=9),
            preserve_default=False,
        ),
    ]
