# Generated by Django 3.1.4 on 2020-12-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0003_auto_20201207_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
