# Generated by Django 3.1.4 on 2020-12-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0004_clientes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('sueldoBase', models.DecimalField(decimal_places=1, max_digits=8)),
                ('sueldoImponible', models.DecimalField(decimal_places=1, max_digits=8)),
                ('bonos', models.DecimalField(decimal_places=1, max_digits=8)),
                ('Total_haberes', models.DecimalField(decimal_places=1, max_digits=8)),
                ('SIS', models.DecimalField(decimal_places=1, max_digits=8)),
                ('ACHS', models.DecimalField(decimal_places=1, max_digits=8)),
                ('AFC', models.DecimalField(decimal_places=1, max_digits=8)),
                ('sueldos', models.DecimalField(decimal_places=1, max_digits=8)),
                ('sueldo_liquido', models.DecimalField(decimal_places=1, max_digits=8)),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, max_digits=8)),
                ('gratificaciones', models.DecimalField(decimal_places=1, max_digits=8)),
                ('costo_hora', models.DecimalField(decimal_places=1, max_digits=8)),
                ('costo_dia', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
    ]
