# Generated by Django 3.1.4 on 2020-12-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0005_trabajadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trabajadores',
            name='id',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='trabajador_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
