# Generated by Django 3.1.4 on 2020-12-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0006_auto_20201208_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='cliente_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='trabajadores',
            old_name='trabajador_id',
            new_name='id',
        ),
    ]
