# Generated by Django 3.1.4 on 2020-12-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0007_auto_20201208_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
