# Generated by Django 3.1.4 on 2020-12-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0007_auto_20201209_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorias',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
