# Generated by Django 3.1.4 on 2020-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0008_auto_20201209_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
