# Generated by Django 3.1.4 on 2020-12-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0009_auto_20201209_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petroleo',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='petroleo',
            name='valor_anterior',
        ),
    ]
