# Generated by Django 3.1.4 on 2020-12-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0010_auto_20201210_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=3)),
                ('conductor', models.CharField(max_length=100)),
                ('horas_conductor', models.DecimalField(decimal_places=1, max_digits=8)),
                ('cant_ayudantes', models.IntegerField()),
                ('nombre_asistente1', models.CharField(max_length=100)),
                ('horas_asistente1', models.DecimalField(decimal_places=1, max_digits=8)),
                ('nombre_asistente2', models.CharField(max_length=100)),
                ('horas_asistente2', models.DecimalField(decimal_places=1, max_digits=8)),
                ('valor_colaciones', models.DecimalField(decimal_places=1, max_digits=8)),
                ('lugar_origen', models.CharField(max_length=150)),
                ('lugar_destino', models.CharField(max_length=150)),
                ('lugar_servicio', models.CharField(max_length=150)),
                ('suma_peajes', models.DecimalField(decimal_places=1, max_digits=9)),
                ('costo_total', models.DecimalField(decimal_places=1, max_digits=9)),
                ('utilidad', models.DecimalField(decimal_places=1, max_digits=9)),
                ('tarifa', models.DecimalField(decimal_places=1, max_digits=8)),
                ('m3', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='TI',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='arriendo',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='encomiendas',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='gastos_comunes',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='generales',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='insumos_aseo',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='insumos_oficina',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='mantencion_banco',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='patentes',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='permisos_circulacion',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosadministrativos',
            name='ropa_trabajadores',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='cordel',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='electricidad',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='gas_grua',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='insumos_epp',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='insumos_planta',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='mantencion_maquinaria',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastosproduccion',
            name='petroleo',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastostotales',
            name='costo_operativo_dia',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastostotales',
            name='costo_operativo_hora',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastostotales',
            name='costo_operativo_mes',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastostotales',
            name='sueldos',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastostotales',
            name='total_administrativos',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastostotales',
            name='total_asesorias',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gastostotales',
            name='total_produccion',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='petroleo',
            name='valor_actual',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='ACHS',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='AFC',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='SIS',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='Total_haberes',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='bonos',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='costo_dia',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='costo_hora',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='gratificaciones',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='sueldoBase',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='sueldoImponible',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='sueldo_liquido',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='sueldos',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
