# Generated by Django 3.1.4 on 2020-12-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0011_auto_20201211_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='run',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
