# Generated by Django 3.1.4 on 2020-12-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0012_todo_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='fecha',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
