# Generated by Django 3.1.4 on 2020-12-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza', '0013_todo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='kms',
            field=models.DecimalField(decimal_places=1, default=660, max_digits=8),
            preserve_default=False,
        ),
    ]
